version: 2

sources:
  - name: test_orders
    database: intrepid-craft-450709-f9
    schema: test_orders_copy
    tables:
      - name: auth_accounts
      - name: auth_invitations
      - name: auth_users
      - name: billing_discount_actions
      - name: billing_discount_code_usages
      - name: billing_discount_codes
      - name: billing_licenses
      - name: billing_order_history
      - name: billing_orders
      - name: billing_products
      - name: billing_user_cart
      - name: elearingcontent_learn_elements
      - name: elearingcontent_published_elements
      - name: elearingcontent_unpublished_elements
      - name: elearingcontent_video_subtitles
      - name: email_personalized_email_templates
      - name: files_file_description
      - name: instructor_instructors
      - name: learn_content_submissions
      - name: learn_ihk_certificate_orders
      - name: learn_tree_states
      - name: learn_tree_unlocked_states
      - name: level_definitions
      - name: license_definitions
      - name: report_reports
      - name: trees_published_nodes
      - name: tress_unpublished_nodes
      - name: ads_insights_delivery_platform_and_device_platform
  - name: google_analytics
    database: intrepid-craft-450709-f9
    schema: ga4_copy
    tables:
      - name: events_*
      - name: events_intraday_*
      - name: pseudonymous_users_*
      - name: users_*
  - name: google_ads
    database: intrepid-craft-450709-f9
    schema: google_ads
    tables:
      - name: p_ads_CampaignStats_8244972127


