version: 2

sources:
  - name: raw_airbyte_billing_orders
    database: intrepid-craft-450709-f9
    schema: raw_test_orders
    tables:
      - name: test_orders_raw__stream_billing_orders
  - name: raw_test_billing_orders
    database: intrepid-craft-450709-f9
    schema: raw_billing_orders
    tables:
      - name: billing_orders